env:
   global:
     - CONAN_REFERENCE="hdps-core/0.1.0"
     - CONAN_USERNAME="lkeb"
     - CONAN_CHANNEL="stable"     
     - CONAN_LOGIN_USERNAME="admin"
     - CONAN_PASSWORD=$CONAN_PASSWORD_SECRET  
     - CONAN_BLDRVNLW_TOKEN=$CONAN_GITACCESS_TOKEN
     - CONAN_UPLOAD="http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local"
     - CONAN_STABLE_BRANCH_PATTERN="master"
     - CONAN_SKIP_CHECK_CREDENTIALS=1
     - CONAN_UPLOAD_ONLY_WHEN_STABLE=1

linux: &linux
   os: linux
   dist: xenial
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        env: 
            - CONAN_GCC_VERSIONS=9 
            - CONAN_DOCKER_IMAGE=conanio/gcc9
            - CONAN_BUILD_TYPES=Release
            - CONAN_ARCHS=x86_64
      - <<: *osx
        osx_image: xcode10.3
        env: 
            - CONAN_APPLE_CLANG_VERSIONS=10.0
            - CONAN_BUILD_TYPES=Release
            - CONAN_ARCHS=x86_64

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - python -c "from githubtools import set_build_status, State; set_build_status('build_trigger.json', 'CONAN_BLDRVNLW_TOKEN', '$TRAVIS_BUILD_WEB_URL', 'Travis', State.pending)"
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
  
after_success:
  - python -c "from githubtools import set_build_status, State; set_build_status('build_trigger.json', 'CONAN_BLDRVNLW_TOKEN', '$TRAVIS_BUILD_WEB_URL', 'Travis', State.success)"
  
after_failure:  
  - python -c "from githubtools import set_build_status, State; set_build_status('build_trigger.json', 'CONAN_BLDRVNLW_TOKEN', '$TRAVIS_BUILD_WEB_URL', 'Travis', State.failure)"