build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_REFERENCE: "hdps-core/0.1.0"
    CONAN_USERNAME: "lkeb"
    CONAN_LOGIN_USERNAME: "admin"
    CONAN_PASSWORD:
        secure: g+1lNdgrCLmyKNf3KvbHSln5A1H7BsVhsMsIbwgo+UU=
    CONAN_BLDRVNLW_TOKEN:
        secure: eIgpHLriHQm+3JYcUR3PDOHtukwUPFtXmK88tGgHu3xLeSi2v1A4luxPtrVdocBf    
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
    CONAN_REMOTE: lkebconan
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    CONAN_OPTIONS: "hdps-core:shared=True"
    APPVEYOR_BUILD_URL: "${APPVEYOR_URL}/project/${APPVEYOR_ACCOUNT_NAME}/${APPVEYOR_PROJECT_NAME}/builds/${APPVEYOR_BUILD_ID}"
    
    matrix:
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#          CONAN_VISUAL_VERSIONS: 12
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#          CONAN_VISUAL_VERSIONS: 14
### Limit build to 2017, x64 , Release, Shared
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
          MINIMUM_CMAKE_VERSION: 3.17
          # CONAN_OPTIONS: "hdps-core:shared=True"
          BUILD_SHARED: True
          
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#          CONAN_VISUAL_VERSIONS: 16

install:
  - ps: $triggerdata = Get-Content 'build_trigger.json' | Out-String | ConvertFrom-Json; Update-AppveyorBuild -CommitId $triggerdata.head_commit.id
  - ps: Write-Host $env:APPVEYOR_REPO_COMMIT 
  - ps: Add-AppveyorMessage $env:APPVEYOR_REPO_COMMIT
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install git+https://github.com/bldrvnlw/citools.git#egg=citools
  - pip install -Iv cmake>=%MINIMUM_CMAKE_VERSION%
  - for /f "delims=" %%i IN ('where cmake') do set CONAN_CMAKE_PROGRAM=^"%%i^"
  - echo cmake path is %CONAN_CMAKE_PROGRAM%
  - pip.exe install conan --upgrade 
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

notifications:   
  - provider: Email
    to: 
        - b.van_lew@lumc.nl
    subject: Test hdps-core {{status}}

    message: "URL is {{buildUrl}} Commit ID {{commitId}}. Messages {{jobs.0.messages.0.message}}"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true     
        
build_script:
  - python -c "from citools.githubtools import set_build_status, State; set_build_status('build_trigger.json', '%CONAN_BLDRVNLW_TOKEN%', '%APPVEYOR_BUILD_URL%', 'Appveyor', State.pending)"
  - python build.py

on_success:
  - python -c "from citools.githubtools import set_build_status, State; set_build_status('build_trigger.json', '%CONAN_BLDRVNLW_TOKEN%', '%APPVEYOR_BUILD_URL%', 'Appveyor', State.success)"
  
on_failure:
  -  python -c "from citools.githubtools import set_build_status, State; set_build_status('build_trigger.json', '%CONAN_BLDRVNLW_TOKEN%', '%$APPVEYOR_BUILD_URL%', 'Appveyor', State.failure)"
