build: false

environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_REFERENCE: "hdps-core/0.1.0"
    CONAN_USERNAME: "lkeb"
    CONAN_LOGIN_USERNAME: "admin"
    CONAN_PASSWORD:
        secure: g+1lNdgrCLmyKNf3KvbHSln5A1H7BsVhsMsIbwgo+UU=
    CONAN_CHANNEL: "stable"
    VS150COMNTOOLS: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\Common7\\Tools\\"
    CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
    CONAN_REMOTE: lkebconan
    CONAN_STABLE_BRANCH_PATTERN: "release/*"
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    
    matrix:
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#          CONAN_VISUAL_VERSIONS: 12
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
#          CONAN_VISUAL_VERSIONS: 14
### Limit build to 2017, x64 , Release, Shared
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CONAN_VISUAL_VERSIONS: 15
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release
          CONAN_VISUAL_RUNTIMES: MD
          # CONAN_OPTIONS: "hdps-core:shared=True"
          BUILD_SHARED: True
          
#        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
#          CONAN_VISUAL_VERSIONS: 16

install:
  - ps: $triggerdata = Get-Content 'build_trigger.json' | Out-String | ConvertFrom-Json; Update-AppveyorBuild -CommitId $triggerdata.head_commit.id
  - ps: Write-Host $env:APPVEYOR_REPO_COMMIT 
  - ps: Add-AppveyorMessage $env:APPVEYOR_REPO_COMMIT
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade 
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: ci-cd
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
    
# state: error failure pending success      
  - provider: Webhook
    url: https://api.github.com/repos/hdps/core/statuses/{{jobs.0.messages.0.message}}
    method: POST 
    content_type: application/json
    headers: 
        Authorization:
            secure: FQyZkOaEbATRwkS61M3rYhRZxRw2s5Mswx9eYjKJ+STcAm3qlm5gHcp8dSe4FKP/  
    body: >-
        {
          "state": "{{#passed}}success{{/passed}}{{#failed}}failure{{/failed}}",
          "target_url": {{buildUrl}},
          "description": "Appveyor result! {{buildUrl}}",
          "context": "baldur/testing"
        }
    on_build_success: always
    on_build_failure: true
    on_build_status_changed: true 

  - provider: Email
    to: 
        - b.van_lew@lumc.nl
    subject: Test hdps-core {{status}}
#    message: "URL is {{buildUrl}} Commit ID {{commitId}}. Messages {{jobs.0.messages.0.message}}"
    message: "URL is {{buildUrl}} Commit ID {{commitId}}. Messages {{jobs.0.messages.0.message}}"
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true     
        
test_script:
  - python build.py
  
after_test:  
